#!/usr/bin/env bash
# Run by `make book` after `quarto render` (see note in
# mermaid-pre-render.sh on why this isn't wired into _quarto.yml's
# post-render hook instead - kept as a plain script for symmetry).
#
# Deletes the disposable .qmd files generated by
# scripts/mermaid-pre-render.sh, leaving only the Obsidian-native
# .md sources in the vault.
set -euo pipefail
cd "$(dirname "$0")/.."

for f in *.md; do
  [ "$f" = "CLAUDE.md" ] && continue
  base="${f%.md}"
  rm -f "${base}.qmd"
done
